export const WEATHER_FETCH_REQUEST = "WEATHER_FETCH_REQUEST";
export const WEATHER_FETCH_SUCCESS = "WEATHER_FETCH_SUCCESS";
export const WEATHER_FETCH_FORECAST_SUCCESS = "WEATHER_FETCH_FORECAST_SUCCESS";
export const WEATHER_FETCH_FAILED = "WEATHER_FETCH_FAILED";
